import { type NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Introduction from "../components/Introduction";
import Logo from "../components/Logo";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>imskanand</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-slate-500">
        <nav className="z-24 fixed top-0 right-0 left-0 m-0 mb-24 mt-0 w-full rounded-xl">
          <Logo />
        </nav>
        <section className="mt-12 min-h-screen">
          <Introduction />
          <About />
          <Skills />
          <Projects />
          <Contact />
        </section>
      </main>
    </>
  );
};

export default Home;
