import { type NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Introduction from "../components/Introduction";
import Logo from "../components/Logo";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>imskanand</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-500">
        <header>
          <Logo />
        </header>
        <section className="min-h-screen">
          <Introduction />
          <About />
          <Skills />
          <Projects />
        </section>
      </main>
    </>
  );
};

export default Home;
